language: android

branches:
  only:
    - master

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-22

install: true

before_script: chmod +x gradlew

script:
  - chmod +x ./gradlew